version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app

hooks:
  BeforeInstall:
    - location: scripts/stop_docker.sh
      timeout: 60
  AfterInstall:
    - location: scripts/start_docker.sh
      timeout: 120
