version: 0.0
os: linux

files:
  - source: scripts/
    destination: /home/ec2-user/app/scripts
  - source: Dockerfile
    destination: /home/ec2-user/app
  - source: nginx.conf
    destination: /home/ec2-user/app

hooks:
  BeforeInstall:
    - location: scripts/permissions.sh
      timeout: 300
      runas: ec2-user

  ApplicationStop:
    - location: scripts/stop_docker.sh
      timeout: 300
      runas: ec2-user

  AfterInstall:
    - location: scripts/start_docker.sh
      timeout: 300
      runas: ec2-user
