version: 0.0
os: linux

hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 300
      runas: root

  BeforeInstall:
    - location: scripts/permissions.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/start_docker.sh
      timeout: 300
      runas: root
