version: 0.0
os: linux

hooks:
  BeforeInstall:
    - location: scripts/permissions.sh
      runas: root

  ApplicationStop:
    - location: scripts/stop_docker.sh
      runas: root

  AfterInstall:
    - location: scripts/start_docker.sh
      runas: root
