version: 0.0
os: linux

hooks:
  BeforeInstall:
    - location: scripts/permissions.sh
      runas: root

  ApplicationStop:
    - location: scripts/stop.sh
      runas: root

  AfterInstall:
    - location: scripts/start.sh
      runas: root
